"""
Reserves Nowcast data source.

Serves the ParraMacro reserves nowcast JSON (Ferranti-style model)
which provides real-time estimates of the currency composition of
global foreign exchange reserves between quarterly COFER releases.

Data is generated by the sovereign_debt/run_reserves_nowcast.py pipeline
and stored as a static JSON file in data/reserves_nowcast.json.
"""

import json
import logging
import os
import threading
import time

logger = logging.getLogger(__name__)

CACHE_TTL = 3600  # 1 hour (file rarely changes)

_APP_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
_DATA_FILE = os.path.join(_APP_ROOT, 'static', 'data', 'reserves_nowcast.json')
# Fallback to data/ if static/data doesn't exist
if not os.path.exists(_DATA_FILE):
    _DATA_FILE = os.path.join(_APP_ROOT, 'data', 'reserves_nowcast.json')


class NowcastCache:
    """Thread-safe cache for nowcast JSON data."""

    def __init__(self):
        self._lock = threading.RLock()
        self._data = None
        self._last_load = 0

    def get(self):
        with self._lock:
            if self._data and (time.time() - self._last_load) < CACHE_TTL:
                return self._data

        data = _load_nowcast()
        if data:
            with self._lock:
                self._data = data
                self._last_load = time.time()
            return data

        with self._lock:
            return self._data or _empty_result()

    def clear(self):
        with self._lock:
            self._data = None
            self._last_load = 0


_cache = NowcastCache()


def _empty_result():
    return {
        'metadata': {
            'model_version': '1.0.0',
            'error': 'No nowcast data available',
        },
        'historical': {'periods': [], 'shares': {}},
        'nowcast': None,
        'diagnostics': {},
    }


def _load_nowcast():
    """Load the nowcast JSON file."""
    try:
        if not os.path.exists(_DATA_FILE):
            logger.warning(f"Nowcast file not found: {_DATA_FILE}")
            return None

        with open(_DATA_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)

        logger.info(
            f"Nowcast data loaded: base={data.get('metadata', {}).get('cofer_base_period', '?')}, "
            f"through={data.get('metadata', {}).get('nowcast_through', '?')}"
        )
        return data

    except Exception as e:
        logger.error(f"Failed to load nowcast data: {e}")
        return None


def get_nowcast_data():
    """Public API: returns cached nowcast data."""
    return _cache.get()
